Add a small sleep so haproxy has time to fully exit and free port 80
Avoids this certbot error:
certbot.errors.PluginError: Could not bind TCP port 80 because it is already in use by another process on this system (such as a web server). Please stop the program in question and then try again.

See logs in: /var/log/letsencrypt/letsencrypt.log*